# Generated by Django 4.1 on 2023-06-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=300)),
                ("short_url", models.URLField(max_length=30)),
                ("times_followed", models.PositiveIntegerField(default=0)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
